# This workflow will publish the latest master branch to github pages

name: Node.js Package

on:
  push:
    branches: [master]

jobs:
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run deploy
